### ISSUE TITLE
Macro system needs some adaptations to work with LFC

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-uc#77]
A few modifications are needed to work with LFC.
1. We must split out DEFINE_TIMER_STRUCT and DEFINE_TIMER_CTOR since first goes in a header file and second goes in a source file.
2. We must expose (offset, period) and (min_delay, min_spacing) as ctor arguments, not hardcoded. This is to support setting those based on reactor parameters

**Comment by tanneberger** [comment]
see #82

**Comment by erlingrj** [comment]
Yes, all of them are affected. And I have done it as part of #71
